# Generated by Django 6.0.4 on 2026-04-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64, unique=True)),
                ('recipient', models.CharField(max_length=100)),
                ('amountSat', models.BigIntegerField()),
                ('feeSatPerVB', models.FloatField()),
                ('sizeBytes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('replaced', 'Replaced')], default='pending', max_length=20)),
                ('confirmations', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('replacedBy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='core.transaction')),
            ],
        ),
    ]
