# Generated by Django 6.0.4 on 2026-04-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='txid',
            new_name='txId',
        ),
    ]
